Refactor2C 6 (#250)
* refactor: InterpKey moved to bind.pyx
* refactor: prepare to use BaseTrajData_t directly
* refactor: interpolate_at moved to C
* refactor: BaseTrajSeqT embeds TrajBaseSeq_t
* refactor: use ErrorCode for returns
* refactor: improved C/Cython errors handling
* refactor: BaseTrajSeq_t_get_at_slant_height moved to C
* refactor: BaseTrajSeq_t_get_raw_item
* refactor: BaseTrajData_t_interpolate moved to C
* chore: removed unused references
* refactor: BaseTrajSeq_t_get_item moved to C
* refactor: BaseTrajSeq_t_get_at moved to C
* fix: changed ErorrCode(s) sign
* refactor: removed redundand definitions
* refactor: use direct C calls
* refactor: added INPUT_ERROR
* refactor: added logging to C sources
* fix: C source logging can be enabled with BCLIB_LOG_LEVEL env var
* chore: ruff config updated, checks passsing
* refactor: _find_apex wraps Engine_t_find_apex
* feature: added Engine_t_ERR macros to handle Engine_t error messages
* bug: attempt to handle math domain error in _find_apex
* fix: fixed math domain error in Engine_t_find_apex
* fix: cross-platform macro fix for Engine_t_ERR
* refactor: improved C logging
* refactor: get engine error from C
* refactor: Engine_t_error_at_distance moved to C and optimized
* refactor: attempt to move Engine_t_init_zero_calculation to C
* fix: fix for MSVC
* refactor: Engine_t_init_zero_calculation moved to C
* fix: improved apex error handling in C sources
* fix: improved init zero errors handling in Cython sources
* fix: improved INPUT ERRORS handling
* fix: INPUT_ERROR handling
* refactor: ErrorCode extended to return specific errors
* refactor: improoved error code check for BaseTrajSec_t
* refactor: BaseTrajSeq_t_get_at much more readable
* refactor: complete refactoring of base_traj_seq
* refactor: Cython resolves termination_reason in integrate()
fix: ErrorCode checks fix
* chore: cythonization reports update
* refactor: attempt to move Engine_t_zero_angle to C
* refactor: implemented Engine_t_zero_angle
* chore: update cythonization reports
* refactor: Engine_t_range_for_angle moved to C
* refactor: Engine_t_find_max_range moved to C
* fix: avoid goto usage
* refactor: better macroses names and usage
* fix: fix macroses for macos
* fix: typo fix
* CI: limit paralel tests workers to 10
* feature: added simple C error stack implementation for furure errors handling improvements
* refactor: Engine_t_find_zero_angle moved to C
* refactor: attempt to reconstruct error stack
* cleanup: removed useless arguments
* refactor: zero init status flags
* refactor: use TerminationReason flag
* refactor: improved error handling
* chore: improved error stack trace format
```bash
py_ballisticcalc.exceptions.SolverRuntimeError: error code: 0x9, source: py_ballisticcalc_exts/src/engine.c:543 (Engine_t_zero_angle) Zero finding error
Trace:
   [0] py_ballisticcalc_exts/src/rk4.c                    :332  (_integrate_rk4) : [src=0  (SRC_INTEGRATE), code=1  (T_ZERO_DIVISION_ERROR)] fake error
   [1] py_ballisticcalc_exts/src/engine.c                 :121  (Engine_t_integrate) : [src=0  (SRC_INTEGRATE), code=8  (T_RUNTIME_ERROR)] Integration failed:
=> [2] py_ballisticcalc_exts/src/engine.c                 :543  (Engine_t_zero_angle) : [src=2  (SRC_ZERO_ANGLE), code=9  (T_ZERO_FINDING_ERROR)] Zero finding error
```
* chore: cleanup
* refactor: ErrorType to Excteption mapping
* fix: Rider's method fixed